#!/bin/bash
	status=$(ps aux | grep [.]/tgbot | wc -l)
	if [ "$status" -eq 0 ]
then {
	echo "Run bot"
	sleep 10 #delay 10 second
	./tgbot  #run programm
	exit 1
}
else {
	echo "Bot already work"
	exit 1
}
fi;
