#!/bin/bash
for (( ;; )) #forever cycle
do
	ret=$(ps aux | grep [.]/tgbot | wc -l)
	if [ "$ret" -eq 0 ]
then {
	echo "Running tgbot"
        sleep 10  #delay
	./tgbot #command for run program
	#exit 1
}
else 
{
	echo "Bot working!"
	sleep 10
	#exit 1
}
fi;
done
